config/routes.rb
ChunkyBaconCorp::Application.routes.draw do
  get "site/home"

  resources :orders
  resources :customers

  root to: 'site#home'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :city, :name, :state

  has_many :orders
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :customer, :price, :quantity, :customer_name

  belongs_to :customer

  validates :quantity, :presence => true

  before_save :calculate_price

  def calculate_price
    self.price = self.quantity * 5
  end

  def customer_name=(str)
    self.customer = Customer.find_or_create_by_name(str)
  end

  def customer_name
    self.customer.name if self.customer
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    @order = Order.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(params[:order])

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render json: @order, status: :created, location: @order }
      else
        format.html { render action: "new" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ChunkyBaconCorp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header>
    <div class='logo'>
      <%= link_to "ChunkyBaconCorp!", root_path %>
    </div>
    <ul id='nav'>
      <li>
        <%= link_to 'Orders', orders_path %>
      </li>
      </li>
      <li>
        <%= link_to '+ New Order', new_order_path %>
      </li>
    </ul>
  </header>

  <div id='content'>
    <%= yield %>
  </div>

  <footer>
    <ul>
      <li>
        Copyright <%= Time.now.year %> ChunkyBaconCorp
      </li>
      <li>
        <%= link_to "Twitter", "http://twitter.com/chunkybaconcorp" %>
      </li>
    </ul>
  </footer>


</body>
</html>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>


  <% if @order.errors.any? %>
    <div class="alert fade in">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>

  <% end %>

  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label 'Your Name' %><br />
    <%= f.text_field :customer_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Orders</h1>

<table>
  <tr>
    <th>Quantity</th>
    <th>Price</th>
    <th>Customer</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @orders.each do |order| %>
  <tr>
    <td><%= order.quantity %></td>
    <td><%= order.price %></td>
    <td><%= order.customer_name %></td>
    <td><%= link_to 'Show', order %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>Order More Chunky Bacon</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <b>Quantity:</b>
  <%= @order.quantity %>
</p>

<p>
  <b>Price:</b>
  $<%= @order.price %>
</p>

<p>
  <b>Customer:</b>
  <%= @order.customer_name %>
</p>


<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/site/home.html.erb
<div>
  <iframe width="900" height="480" src="http://www.youtube.com/embed/4M6qAMMqFhI" frameborder="0" allowfullscreen></iframe>
</div>
<div style='float: left; width: 600px; margin-right: 20px;'>
  <h1>ALL BACON ALL CHUNKY ALL THE TIME!</h1>
  <p>
    <img src='http://4.bp.blogspot.com/-HX7l3B-dPXY/UN0FeGidWHI/AAAAAAAADZE/FF9svNR700I/s1600/crispy-bacon.jpg'>
  </p>
  <p>
    Bacon ipsum dolor sit amet bacon leberkas chicken meatloaf. Meatball sirloin ribeye, tongue sausage ball tip prosciutto cow andouille tail. Drumstick beef spare ribs, frankfurter shank bacon filet mignon. Pork belly t-bone ham hock meatloaf pig short loin strip steak shoulder. Frankfurter rump ground round flank pork belly meatloaf spare ribs ham hock ribeye jowl cow ham. Pork loin cow swine, boudin jerky turkey t-bone drumstick.
  </p>
  <p>
    <ul>
      <li>Bacon is good.</li>
      <li>FDA Approved.</li>
      <li>Women who are pregnant or operating heavy machinery should definitely eat bacon.</li>
      <li>Bacon.</li>
    </ul>
  </p>

<div id="myCarousel" class="carousel slide">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <!-- Carousel items -->
  <div class="carousel-inner">
    <div class="active item"><img src='http://4.bp.blogspot.com/-EAK6KpsLh1M/Tn-2pFmNBvI/AAAAAAAAAtk/P5YmnG9RQno/s1600/bacon-love.jpg' width='600px'></div>
    <div class="item"><img src='http://cdn.sheknows.com/articles/candied-bacon.jpg' width='600px'></div>
    <div class="item"><img src='http://cdn.instructables.com/FAN/NWX6/CQHEXCFLZ85/FANNWX6CQHEXCFLZ85.LARGE.jpg' width='600px' ></div>
  </div>
  <!-- Carousel nav -->
  <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>


<div style='float: left; width: 300px;'>
  <p>
    Bacon boudin rump jowl prosciutto pork doner pork loin beef ribs pork chop tongue tail. Tenderloin short loin doner meatloaf ham hock chicken brisket pancetta shank jerky sausage capicola turducken flank strip steak. Spare ribs bresaola pastrami, strip steak sausage sirloin jerky pork chop pork loin filet mignon prosciutto cow fatback meatloaf. Pork frankfurter meatball andouille sirloin biltong kielbasa short loin bresaola corned beef. Rump boudin turkey shoulder beef ribs ball tip tongue ham hock. Boudin bacon short loin chicken, biltong ham pork belly frankfurter pancetta pork chop ham hock pork loin rump kielbasa jowl.
  </p>
  <h2>Put some bacon on it!</h2>
  <p>
    Beef ribs short ribs pork t-bone. Ham hock rump beef filet mignon pork belly pig fatback shoulder beef ribs, tongue frankfurter sirloin turkey. Shankle spare ribs chicken pancetta flank, salami meatball pork belly pork chop ham hock chuck brisket pastrami. Ribeye turkey pork belly hamburger meatball pork loin biltong bresaola chicken pastrami beef ribs ground round ham drumstick. Spare ribs brisket shankle pork. Capicola rump shankle fatback salami shank doner hamburger pastrami shoulder tri-tip t-bone ham hock pork chop jerky.
  </p>
</div>